// ── THE DATE THAT WAS ALWAYS ON THE PAGE AND NOBODY READ ────────────
//
// Oliver, 15 Sep 2026, pasting a Facebook event URL: "this is a Facebook event
// with a date." It is, and neither API Direct nor any permitted fetch gets that
// date out of Facebook. So the answer is not Facebook. It is that most ticket
// systems and a good share of organiser sites publish the same fact as
// schema.org JSON-LD on a page THIS PIPELINE ALREADY FETCHES, and pageScan.js
// has never looked at it. Every one of those dates has been walked past.
//
//   <script type="application/ld+json">
//   { "@type": "Event", "name": "...", "startDate": "2026-07-25T10:00+02:00",
//     "endDate": "2026-07-27", "location": { ... } }
//
// That is a machine-readable date, published by the organiser, on their own
// page, with no API cost and no terms to argue about. It is the best date source
// available to this project and it was sitting in the HTML the whole time.
//
// ── WHAT THIS FILE DOES NOT DO ──────────────────────────────────────
//
// It does not decide anything. It reads a page's structured events and hands
// them over as claims. Which claim wins is dateAuthority.js, and the split is
// deliberate: a reader that also ranked would make the ranking untestable
// without a page in front of it.
//
// It also does not trust the page's own opinion of what it is. An organiser's
// front page carries a JSON-LD Event for every listing in its sidebar, so a
// caller asking about one festival can get eleven events back. Matching the
// right one is the caller's job and `eventsInPage` returns all of them with
// their names, rather than picking one and being wrong quietly.

const nodes = (v) => (Array.isArray(v) ? v : v == null ? [] : [v]);

// @type can be a string or an array, and Vite-era organiser sites emit both.
const isEvent = (n) => {
  const t = n && (n["@type"] ?? n.type);
  return nodes(t).some(x => /(?:^|[^a-z])event$/i.test(String(x)));
};

// A graph, a list, a single object, or a list of graphs. All four turn up, and
// the flattening is done here so no caller has to know that.
const flatten = (parsed, depth = 0) => {
  if (!parsed || depth > 4) return [];
  if (Array.isArray(parsed)) return parsed.flatMap(p => flatten(p, depth + 1));
  if (typeof parsed !== "object") return [];
  const out = [parsed];
  if (parsed["@graph"]) out.push(...flatten(parsed["@graph"], depth + 1));
  // A SubEvent is a real event with its own date: a festival's individual days.
  if (parsed.subEvent) out.push(...flatten(parsed.subEvent, depth + 1));
  return out;
};

// ── THE DATE, AS A DAY ──────────────────────────────────────────────
//
// startDate is an ISO 8601 string in the spec and is a date, a datetime, or a
// datetime with an offset in the wild. Only the day is kept: every date this
// project stores is a day, and an hour kept here would be an hour nothing else
// can read.
//
// Parsed by pattern rather than by `new Date()`, because `new Date("2026-07-25")`
// is UTC midnight and in Copenhagen that is still the 25th, while
// `new Date("25-07-2026")` is an Invalid Date in one engine and a guess in
// another. A regex that only accepts the shape the spec promises cannot do
// either.
const ISO_DAY = /^(\d{4})-(\d{2})-(\d{2})(?:[T ]|$)/;

export const ldDay = (value) => {
  const m = ISO_DAY.exec(String(value || "").trim());
  if (!m) return "";
  const [, y, mo, d] = m;
  const month = Number(mo), dayNum = Number(d);
  if (month < 1 || month > 12 || dayNum < 1 || dayNum > 31) return "";
  return `${y}-${mo}-${d}`;
};

// ── EVERY JSON-LD BLOCK IN A PAGE ───────────────────────────────────
//
// One bad block does not lose the good ones. Sites emit trailing commas, HTML
// comments wrapped around the JSON, and occasionally two blocks where one is
// generated by a plugin and broken. Each is parsed in its own try.
export const ldBlocks = (html) => {
  const out = [];
  const re = /<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(String(html || ""))) !== null) {
    const raw = String(m[1] || "")
      .replace(/^\s*<!--/, "").replace(/-->\s*$/, "")
      .trim();
    if (!raw) continue;
    try { out.push(JSON.parse(raw)); } catch { /* one broken block is not a broken page */ }
  }
  return out;
};

// ── THE EVENTS, AS CLAIMS ───────────────────────────────────────────
//
// `url` is the page the block was found on, not the event's own url field: the
// claim is "this page says this", and the ranking in dateAuthority.js is about
// WHO said it. An organiser page linking a Facebook event does not make Facebook
// the source of a date read off the organiser's own HTML.
export const eventsInPage = (html, pageUrl = "") => {
  const seen = new Set();
  const out = [];
  ldBlocks(html).forEach(parsed => {
    flatten(parsed).filter(isEvent).forEach(node => {
      const date = ldDay(node.startDate);
      if (!date) return;
      const name = String(node.name || "").trim();
      const key = `${name.toLowerCase()}|${date}`;
      if (seen.has(key)) return;
      seen.add(key);
      out.push({
        name,
        date,
        dateEnd: ldDay(node.endDate) || "",
        // Carried because an organiser marking an event cancelled or postponed
        // is the single most useful thing on this page and it is one field
        // away. EventCancelled and EventPostponed are the spec's own words.
        status: String(node.eventStatus || "").replace(/^https?:\/\/schema\.org\//i, ""),
        url: pageUrl,
      });
    });
  });
  return out;
};

// ── AND THE ONE THAT IS ABOUT THIS ROW ──────────────────────────────
//
// A page with one event needs no matching. A page with eleven needs the caller's
// name, and a wrong match is worse than no match, so the bar is that the names
// share a distinctive run of letters rather than that they look similar.
//
// Returns null rather than a best guess when nothing matches, because "no date
// found" is a true answer and "probably this one" is how a festival gets another
// festival's dates.
const squash = (v) => String(v || "").toLowerCase().normalize("NFC").replace(/[^a-z0-9æøå]/g, "");

export const eventForName = (events, name) => {
  const list = Array.isArray(events) ? events : [];
  if (!list.length) return null;
  const want = squash(name);
  if (!want) return list.length === 1 ? list[0] : null;
  const exact = list.find(e => squash(e.name) === want);
  if (exact) return exact;
  // Six characters, the same floor accountFits uses in socialAccounts.js, and
  // for the same reason: shorter than that and half of Denmark matches.
  const near = list.filter(e => {
    const got = squash(e.name);
    return got.length >= 6 && want.length >= 6 && (got.includes(want) || want.includes(got));
  });
  if (near.length === 1) return near[0];
  // Several plausible matches is not a match. Two of a festival's days both
  // carrying its name is exactly this case, and picking the first would publish
  // day two as the start date.
  return list.length === 1 && !want ? list[0] : null;
};

// The claim shape dateAuthority.reconcileDate expects, so the two files meet at
// one object rather than at a convention nobody wrote down.
export const claimFromEvent = (event, { at = new Date() } = {}) => {
  if (!event || !event.date) return null;
  const d = at instanceof Date && !Number.isNaN(at.getTime()) ? at : new Date();
  return { date: event.date, dateEnd: event.dateEnd || "", url: event.url || "", at: d.toISOString() };
};
