// ── WHERE THE TILE URL LIVES ─────────────────────────────────────────
//
// Oliver, 18 Aug 2026, holding the Stamen Watercolor endpoint: "so where do I
// put this then?"
//
// In three places, as it turned out, which is the answer this file exists to
// stop being true. `L.tileLayer("https://tile.openstreetmap.org/...")` was
// written out verbatim in GuideRouteMap.jsx, PlaceMiniMap.jsx and
// LeafletMap.jsx, each with its own maxZoom and its own attribution string.
// Three copies of one decision is the exact habit that has already cost this
// codebase two disagreeing walking-time estimates, two event-type lists, four
// coordinate lookups and a `daysUntil`. Swapping a basemap by hand-editing three
// files works once and then one of them gets missed.
//
// So: one style table, read by all three.
//
// ── AND A BASEMAP IS THREE THINGS, NOT ONE ──────────────────────────
// This is the part that bites if you only change the URL. A tile layer is a URL
// AND a maximum zoom AND an attribution, and all three are properties of the
// provider rather than of the map showing it:
//
//   maxZoom      Watercolor tops out at 16 and the original tileset has gaps
//                above that. Leaving 19 in place makes Leaflet request tiles
//                nobody has, and you get grey holes when somebody zooms in —
//                which reads as "this map is broken", not "this map is antique".
//
//   attribution  Stadia require three credits: Stadia Maps, Stamen Design and
//                OpenStreetMap contributors. That is a licence condition, not a
//                courtesy, and it is on a paid product. Read their terms for
//                commercial use before this ships.
//
//   filter       See the note on `filter` below. This is the one that will make
//                you think Watercolor looks terrible when it does not.
export const TILE_STYLES = {
  // What the app has always used: OpenStreetMap, inverted to dark so it sits in
  // the dark brand. Kept as the default for the Studio map and the little map on
  // a place page, where a dark panel is the right answer.
  dark: {
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    maxZoom: 19,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    // The dark inversion, moved here from the single `.gemlyx-tiles` rule in
    // App.jsx so the filter travels with the tiles it was written for. A style
    // whose tiles are already painted must NOT inherit it.
    filter: "invert(1) hue-rotate(189deg) brightness(0.92) contrast(1.12) saturate(0.35)",
  },

  // ── THE CHART ─────────────────────────────────────────────────────
  // Stamen Watercolor, hosted by Stadia Maps. Their own description: "reminiscent
  // of hand drawn maps... raster effect area washes and organic edges over a
  // paper texture." Which is the treasure map, with real Danish geography under
  // it rather than a coastline an image generator invented.
  //
  // THE FILTER IS EMPTY AND THAT IS THE POINT. Watercolor is already painted. Run
  // the dark inversion over it and you get an inverted watercolour mess, which
  // looks like the tiles are wrong rather than like the filter is. If this style
  // ever looks bad, check this line first.
  //
  // tiles-eu is not a preference either: it is the European endpoint, which is
  // closer to Danish readers and keeps the request inside the EU.
  chart: {
    url: "https://tiles-eu.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg",
    // 16, not 19. See the note above.
    maxZoom: 16,
    attribution: '&copy; <a href="https://stadiamaps.com/" target="_blank" rel="noreferrer">Stadia Maps</a>'
      + ' &copy; <a href="https://stamen.com/" target="_blank" rel="noreferrer">Stamen Design</a>'
      + ' &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> contributors',
    filter: "",
  },
};

export const DEFAULT_TILE_STYLE = "dark";

// One call site shape for all three components. Returns exactly the object
// L.tileLayer's options want, plus the className the filter hangs off.
//
// An unknown style name falls back to the default rather than returning
// undefined and blanking the map: a typo in a prop should cost you the styling
// you asked for, not the basemap.
export const tileConfig = (style = DEFAULT_TILE_STYLE) => {
  const s = TILE_STYLES[style] || TILE_STYLES[DEFAULT_TILE_STYLE];
  const name = TILE_STYLES[style] ? style : DEFAULT_TILE_STYLE;
  return {
    url: s.url,
    maxZoom: s.maxZoom,
    attribution: s.attribution,
    // Per style, so the filter cannot leak from one basemap onto another. The
    // matching CSS is generated by tileCss() below rather than hand-written in
    // two places.
    className: `gemlyx-tiles gemlyx-tiles-${name}`,
  };
};

// The CSS for every style, built FROM the table so a new style cannot be added
// without its filter arriving with it. Drop the output into the same <style>
// block in App.jsx that the old single `.gemlyx-tiles` rule was in.
export const tileCss = () => Object.entries(TILE_STYLES)
  .filter(([, s]) => s.filter)
  .map(([name, s]) => `.gemlyx-tiles-${name} { filter: ${s.filter}; }`)
  .join("\n");
